# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57ff758b1a141164390f7778fd0665d65a0c6ea399a7d1a145b456d54bed3b38606372f3766c029bb3e8c8d74030cae398a5bb54a6c271ca1ba9e8a8eeadd5c7

test:
  secret_key_base: 3d3e012da154bbd105e06a3b62749e63779ff28961951b079a74cc6f5be2fe20dcb8a9edc80d18e6eaaea04044c4405d3ad5c03fe29e021b9b8bdd2173f44b35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
